### ISSUE TITLE
Not working on a 3.3.5a enUS client for Warmane

### ISSUE THREAD

**Issue by Jaladhjin** [Jnnshschl/WowRdpPatcher#1]
Hello hello!

I was attempting to use this I see it was released in 2020 not sure if you still are active on this at all but I dropped my wow.exe onto the RDP Patcher a command window came up for like a millisecond & I still get the same error when attempting to launch WoW :-(

Is there another way I can perform this to ensure whatever this is doing is running with Elevation if it needs to or whatever?

I've got Local Administrator & read/write access on the machine in question too.

**Comment by Jnnshschl** [comment]
Is it possible for you to share the wow executeable? I think the string may be a bit different than in enGB.

**Comment by Jaladhjin** [comment]
Oh yes of course!

I'm enUS 1 moment

**Comment by Jaladhjin** [comment]
https://gofile.io/d/lJp6Tk

**Comment by Jnnshschl** [comment]
It might failed because you were missing NetCore 3.1 x86, try the new standalone version from here, it worked for me: https://github.com/Jnnshschl/WowRdpPatcher/releases/tag/1.1

If that doesn't work, run the "WowRdpPatcher-Standalone.exe" on the commandline and screenshot it.

**Comment by Jaladhjin** [comment]
Since it's Standalone do I run it first or still drop Wow.exe onto it?

I'll give it all a shot thanks!

And if it doesn't work.. am I running "WowRdpPatcher-Standalone.exe" on the commandline with that file in the Wow.exe directory or from anywhere?

**Comment by Jaladhjin** [comment]
Oh bomb it freakin' worked thanks so much!

I did drag my Wow.exe onto the Standalone & it worked.

Showed me way more info than the version before it did.

Really appreciate it thanks again!

Do you have any other cool client mods like those custom launcher wallpapers or even more useful being able to save password as well as Account Name in the Remember checkbox?

**Comment by Jnnshschl** [comment]
Glad to hear that everything worked fine. Then it really was the missing .Net Framework.

This is the only client mod I made. The other mods you described should only require some MPQ editing, but I have never done such stuff.

**Comment by Jaladhjin** [comment]
Interesting okay good to know.

I'm usually pretty prudent about installing .net framework(s) & vcredist versions but admittedly not 3.1 I think the lowest I've known of is 3.5

Thanks again very much appreciated!
